export const ProjectsData = [
  {
    id: "01",
    title: "MexSabor",
    para: "A modern restaurant website showcasing authentic Mexican cuisine with a bold visual style and clear menu presentation. Designed to highlight brand identity and improve customer engagement.",
    imageLink: "./assets/project01.png",
    webLink: "https://mexsabor.online",
  },
  {
    id: "02",
    title: "Merchandise Me",
    para: "An e-commerce platform for custom merchandise, designed to present products clearly and simplify the ordering process. Emphasis on usability and brand consistency.",
    imageLink: "./assets/project03.png",
    webLink: "https://merchandise-me.com",
  },
  {
    id: "03",
    title: "The Loopy Lamb Crochet",
    para: "A creative e-commerce website for handmade crochet products with a warm, aesthetic design. Focused on product storytelling and smooth browsing experience.",
    imageLink: "./assets/project02.png",
    webLink: "https://merchandise-me.com",
  },
  {
    id: "04",
    title: "Watch Tube",
    para: "A YouTube-style video platform UI built to practice modern layouts, video cards, and responsive design. Focused on clean structure, spacing, and user-friendly browsing.",
    imageLink: "./assets/project07.png",
    webLink: "https://watch-tube-eight.vercel.app/",
  },
  {
    id: "05",
    title: "Watch Showcase",
    para: "A sleek product showcase website designed to highlight watches with smooth layout flow and visual hierarchy. Emphasis on modern UI, typography, and responsive sections.",
    imageLink: "./assets/project08.png",
    webLink: "https://watch-showcase.vercel.app/",
  },
  {
    id: "06",
    title: "Blue Oceans AI",
    para: "A tech-focused website presenting AI solutions with a modern and minimal interface. Built to communicate innovation, trust, and scalability.",
    imageLink: "./assets/project06.png",
    webLink: "https://blueoceansp.ai/home/",
  },
  {
    id: "07",
    title: "A To-Do App",
    para: "A simple and interactive to-do application built to manage daily tasks efficiently. Demonstrates practical use of UI logic, state handling, and clean component-based design.",
    imageLink: "./assets/project09.png",
    webLink: "https://to-do-app-five-snowy.vercel.app/",
  },
  {
    id: "08",
    title: "Jess L Jackson",
    para: "A professional corporate website designed to establish credibility and present services in a clear, organized manner. Focused on clean UI and straightforward navigation.",
    imageLink: "./assets/project05.png",
    webLink: "https://jessljackson.com ",
  },
  {
    id: "09",
    title: "Galaxy Graphics Prints",
    para: "A print services website highlighting custom design and printing solutions. Structured to showcase services, quality visuals, and easy customer contact.",
    imageLink: "./assets/project04.png",
    webLink: "https://galaxygraphicsprints.com ",
  },
  {
    id: "10",
    title: "9toFit",
    para: "A fitness and coaching website focused on health programs, transformations, and client conversions. Built with a clean layout and strong call-to-action sections.",
    imageLink: "./assets/project10.png",
    webLink: "9tofit.nl",
  },
];
